---
- name: install
  become: yes
  environment: 
    http_proxy: "{{ proxy_env }}"
    https_proxy: "{{ proxy_env }}"
  apt: name={{ item }} state=latest update_cache=true
  with_items:
   - nginx
   - php7.2
   - php7.2-fpm
   - composer
   - git

