- name: composer install
  become: yes
  environment: 
    http_proxy: "{{ proxy_env }}"
    https_proxy: "{{ proxy_env }}"
  command: composer install -d /var/www/Hackathon/

- name: thoni jancok
  command: "{{ item }} chdir=/var/www/Hackathon"
  with_items:
  - chmod -R 777 ./storage
  - php artisan key:generate
  - php artisan migrate
