- name: add repo
  become: yes
  environment: 
    http_proxy: "{{ proxy_env }}"
    https_proxy: "{{ proxy_env }}"
  apt_repository: repo='ppa:ondrej/php' state=present

- name: apt update
  environment: 
    http_proxy: "{{ proxy_env }}"
    https_proxy: "{{ proxy_env }}"
  apt:
    update_cache: yes